### ISSUE TITLE
Add the option of transparency

### ISSUE THREAD

**Issue by nugaldea** [hamiltoncj/qgis-kmltools-plugin#6]
Its posibley add a optión to the user define the transparency of the kml export result.
The actual result the kml have 100% opacity; but with some data its better can see the image at the bottom of the shape.
Thanks.

**Comment by agiudiceandrea** [comment]
@nugaldea, please explain in more details what tool exactly are you using and what is you use case.

**Comment by hamiltoncj** [comment]
@nugaldea I have not checked all transparency options, but it does support some aspects of transparency, but would need to know more about what specifically you are missing and how you are using it.

**Comment by hamiltoncj** [comment]
I'm going to close this since there wasn't any additional information provided.
